name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install cppcheck static analysis
      run: sudo apt-get update && sudo apt-get install -y cppcheck
    
    - name: static analysis
      run: cppcheck --enable=all --error-exitcode=1 -istor-scu.c.
      
